fix: add panel IDs to FARM dashboard JSON
Older Grafana versions (8.x) require each panel to have a unique
numeric 'id' field. Without it, DashboardGrid crashes with:
  TypeError: can't access property "toString", a.id is undefined

Signed-off-by: mpyne <mpyne@45drives.com>